server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo

    ##连接池配置信息
    druid:
      #初始连接数
      initial-size: 4
      #最小空闲数
      min-idle: 4
      #最大活动数
      max-active: 20
      #等待超时时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      #验证数据库连接的查询语句，MYSQL是select1
      validation-query: SELECT 1 FROM DUAL
      #空闲时测试（失效连接主要通过testWhileIdle保证）
      test-while-idle: true
      #test-on-borrow,test-on-return 在生产环境一般不开启，主要是性能考虑
      test-on-borrow: false
      test-on-return: false
      #打开PSCache,并指定每个链接上的PSCache大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #通过connectproperties属性来打开mergesql功能：慢sql记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #配置监控统计拦截的filters,去掉后监控界面sql无法统计，‘wall'用于防火墙，此处是filter修改的地方
      filters: stat,wall
      #合并多个DruidDataSource
      useGlobalDataSourceStat: true






